name: CD Pipeline for petclinic project

on:
  push:
    branches:
      - main

jobs:

  deploy-infra-on-prod:
    name: Deploy Terraform Infra changs to Prod 
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: prod
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

  deploy-to-prod:
      name: Deply to Production
      uses: ./.github/workflows/reusable-deploy.yml
      with:
        env: prod

