name: CD Pipeline for petclinic project

on:
  push:
    branches:
      - main

jobs:

  deploy-infra-on-prod:
    name: Deploy Terraform Infra changs to Prod 
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: prod
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

  deploy-to-prod:
      name: Deply to Production
      runs-on: ubuntu-latest
      steps:

        - name: Download Docker image info
          uses: actions/download-artifact@v3
          with:
            name: docker-image-info
            path: .

        - name: Read image SHA
          run: |
            IMAGE_SHA=$(cat image_sha.txt)
            echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV

        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.PET_CLINIC_PEM_FILE }}" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa

        - name: Remote exec on EC2
          run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ vars.EC2_HOST }} << 'EOF'
              docker --version
              if [ $(docker ps -a -q -f name=petclinic-petclinic-container) ]; then
                echo "Container exists. Stopping and removing..."
                sudo docker stop petclinic-petclinic-container
                sudo docker rm petclinic-petclinic-container
              else
                echo "Container does not exist. Skipping removal."
              fi
              sudo docker run -p 8080:8080 -d --name petclinic-petclinic-container ${{ vars.DOCKERHUB_USERNAME }}/petclinic-app:$IMAGE_SHA
            EOF